dummy_topics_list = [    
            ["custom fields", "crm integration"],
            ["what price", "pricing"],
            ["account label", "crm integration"],
            ["customer relationship management", "crm integration"],
            ["outreach.io", "competitors"],
            ["gong.io", "competitors"],
            ["cresta.com", "competitors"],
            ["competitor", "competitors"],
            ["our crm integration", "crm integration"],
            ["another SaaS product", "competitors"],
            ["pricing", "pricing"],
            ["how much", "pricing"],
            ["$100", "pricing"],
            ["smartreach.io company", "competitors"],
            ["too expensive", "pricing"],
            ["intro crm", "crm integration"],
            ["meet", "meeting"],
            ["meeting", "meeting"],
            ["visit", "meeting"],
            ['call', 'meeting'],
            ['faq', 'service'],
            ["conference call", "meeting"],
            ['support service', 'service'],
            ['support', 'service'],
            ['questions', 'service'],
            ['better', 'differentiation'],
            ['worst', 'differentiation'],
            ['killer feature', 'differentiation'],
            ['differentiation', 'differentiation'],
            ['value proposition', 'value proposition'],
            ['increase revenue', 'value proposition'],
            ['revenue', 'value proposition'],
            ['fire employees', 'value proposition'],
            ['save money', 'value proposition'],
            ['save time', 'value proposition']
        ]